# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=release
endif
export config

PROJECTS := homegear-addon

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

homegear-addon: 
	@echo "==== Building homegear-addon ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f homegear-addon.make

clean:
	@${MAKE} --no-print-directory -C . -f homegear-addon.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   release"
	@echo "   debug"
	@echo "   profiling"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   homegear-addon"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
